import pandas as pd
import time

hdong_od_cheongdo_2018 = pd.read_csv('hdong_od_cheongdo_2018.csv', delimiter='|')
hdong_od_cheongdo_2018.to_excel('hdong_od_cheongdo_2018.xlsx', index=False)
time.sleep(50)
hdong_od_cheongdo_2019 = pd.read_csv('hdong_od_cheongdo_2019.csv', delimiter='|')
hdong_od_cheongdo_2019.to_excel('hdong_od_cheongdo_2019.xlsx', index=False)
time.sleep(50)
hdong_od_day_cheongdo_2018 = pd.read_csv('hdong_od_day_cheongdo_2018.csv', delimiter='|')
hdong_od_day_cheongdo_2018.to_excel('hdong_od_day_cheongdo_2018.xlsx', index=False)
time.sleep(50)
hdong_od_day_cheongdo_2019 = pd.read_csv('hdong_od_day_cheongdo_2019.csv', delimiter='|')
hdong_od_day_cheongdo_2019.to_excel('hdong_od_day_cheongdo_2019.xlsx', index=False)
time.sleep(50)
hdong_od_day_cheongdo_2020 = pd.read_csv('hdong_od_day_cheongdo_2020.csv', delimiter='|')
hdong_od_day_cheongdo_2020.to_excel('hdong_od_day_cheongdo_2020.xlsx', index=False)
time.sleep(50)
hdong_od_day_outflow_cheongdo_2018 = pd.read_csv('hdong_od_day_outflow_cheongdo_2018.csv', delimiter='|')
hdong_od_day_outflow_cheongdo_2018.to_excel('hdong_od_day_outflow_cheongdo_2018.xlsx', index=False)
time.sleep(50)
hdong_od_day_outflow_cheongdo_2019 = pd.read_csv('hdong_od_day_outflow_cheongdo_2019.csv', delimiter='|')
hdong_od_day_outflow_cheongdo_2019.to_excel('hdong_od_day_outflow_cheongdo_2019.xlsx', index=False)
time.sleep(50)
hdong_od_day_outflow_cheongdo_2020 = pd.read_csv('hdong_od_day_outflow_cheongdo_2020.csv', delimiter='|')
hdong_od_day_outflow_cheongdo_2020.to_excel('hdong_od_day_outflow_cheongdo_2020.xlsx', index=False)
time.sleep(50)
hdong_od_outflow_cheongdo_2018 = pd.read_csv('hdong_od_outflow_cheongdo_2018.csv', delimiter='|')
hdong_od_outflow_cheongdo_2018.to_excel('hdong_od_outflow_cheongdo_2018.xlsx', index=False)
time.sleep(50)
hdong_od_outflow_cheongdo_2019 = pd.read_csv('hdong_od_outflow_cheongdo_2019.csv', delimiter='|')
hdong_od_outflow_cheongdo_2019.to_excel('hdong_od_outflow_cheongdo_2019.xlsx', index=False)
time.sleep(50)
행정동_매칭테이블 = pd.read_csv('행정동_매칭테이블.csv', delimiter='|')
행정동_매칭테이블.to_excel('행정동_매칭테이블.xlsx', index=False)
time.sleep(50)
